### ISSUE TITLE
Renewal date sync is innacurate

### ISSUE THREAD

**Issue by evolvewebhost** [blesta/plugin-thesslstore#7]
Using the new plugin, the renewal date is off by one month. For a 12 month certificate, blesta shows the renewal date in 11 months.

This is only appearing on the admin side. The client side shows the correct expiration date.[
![screen shot 2017-04-06 at 3 31 01 pm](https://cloud.githubusercontent.com/assets/4961578/24776557/8faef38c-1ade-11e7-93f2-837fc0f17a66.png)
![screen_shot_2017-04-06_at_3_31_13_pm](https://cloud.githubusercontent.com/assets/4961578/24776556/8fadf608-1ade-11e7-9a08-db801de2c2d9.jpg)

](url)

**Comment by TSS-Nick** [comment]
Hello,

I've conducted some testing on my end and was not quite capable of reproducing this issue. Attached is a screenshot I used to test this issue from my personal domain.

![b-test-12months](https://cloud.githubusercontent.com/assets/27232094/24875700/f8cd0564-1df6-11e7-8a93-9d552a7e3f04.PNG)

Can I ask if you're running all the required crons to sync the systems between your billing panel and our system? As I'm seeing the order on our backside and it does indeed have the expiration rate. 

Regards,
Nick

**Comment by evolvewebhost** [comment]
Hi Nick

I do have SSL Certificate Expiration Reminder and SSL Order Synchronization running and Blesta says they last ran this morning.

The Essential SSL is the only one I've got setup so far. I'll have the Comodo SSL setup and active real soon to see if it narrows things down anymore.

Thanks,

Doug

**Comment by evolvewebhost** [comment]
Nick,

If the invitation link is sent out one day for a client to generate the certificate and they do not generate it until days later, this issue occurs. If the client generates the same day the service is provisioned in Blesta, the renewal sync date works.

Hopefully that will help to narrow things down a bit more.

Doug

**Comment by evolvewebhost** [comment]
Hi Nick,
This issue is happening with all Comodo SSL for our clients. If I manually change the date, the cron task overwrites that value with the wrong date again. It's consistently showing that every certificate renews in 11 months instead of 12 months.
Doug

**Comment by TSS-Nick** [comment]
Hello Doug,

Thanks for the update, was able to confirm the issue myself and will have our development team try to resolve the issue in a patch. Once I have an update, I'll let you know via the thread. 

Regards,
Nick

**Comment by pmphillips** [comment]
Please be sure to update the extension patch version also, so that it will be pulled into future
builds. For example, from 1.2.0 to 1.2.1 for the plugin.

Thanks,

Paul

**Comment by evolvewebhost** [comment]
Nick,
Thanks for following up!
Doug

**Comment by evolvewebhost** [comment]
Hi @TSS-Nick ,
Is there a solution for this now?
Thanks!
Doug

**Comment by JReissmueller** [comment]
Hi @TSS-Nick,
I was looking into this a bit and it seems to have been an intentional choice by the developers.  I believe I see it happening on line 212 of the plugin file.  Hope this helps.

Jonathan

**Comment by TSS-Nick** [comment]
Hello Guys,

My apologies for the delayed response! As @JReissmueller had mentioned, our developers have actually made this on purpose to handle the renewal of the certificate(s) at least one month prior to prevent any issues with verification.

Respectfully,
NICHOLAS PERKINS
Systems Application Specialist



[TheSSLStore]<https://www.thesslstore.com/?utm_source=emailsignature&utm_medium=logo&utm_campaign=signaturelogo>



[TSS Hashed Out Blog]<https://www.thesslstore.com/blog/?utm_source=emailsignature&utm_medium=banner&utm_campaign=NSG_SSLStore>



www.theSSLstore.com<https://www.thesslstore.com/?utm_source=emailsignature&utm_medium=logo&utm_campaign=signaturelink> | office: (727) 388-4240 | direct: (727) 820-1165 | fax: (727) 388-3955 | [https://sslhelpdesk.com/images/signature/FB_Icon_Signature.png] <https://www.facebook.com/hashedoutssl/>  [https://sslhelpdesk.com/images/signature/LI_Icon_Signature.png] <https://www.linkedin.com/company/10896505>  [https://sslhelpdesk.com/images/signature/TW_Icon_Signature.png] <https://twitter.com/hashed_out>  | 146 2nd Street North, Suite 201 St. Petersburg, Florida, 33701, US



This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager<mailto:support@theSSLstore.com>. This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. If you are not the intended recipient you are notified that disclosing, copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

**Comment by evolvewebhost** [comment]
Is this the only change to make? Blesta already has terms setup in the client groups so if someone already has net 30, I don't want to add an additional 30 days to a renewal.
